"""add valuation history

Revision ID: f78b25d6940f
Revises: 3eed8d0d1086
Create Date: 2026-07-07 21:18:33.205097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b25d6940f'
down_revision = '3eed8d0d1086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('fair_value_per_share', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('wacc', sa.Float(), nullable=True),
    sa.Column('is_bank_valuation', sa.Boolean(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_history_user_id'))

    op.drop_table('valuation_history')
    # ### end Alembic commands ###
